<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php';
requireAdminCategory('customers');
require_once __DIR__.'/../config/database.php'; require_once __DIR__.'/admin_helpers.php';
$q=trim((string)($_GET['q']??'')); $map=[];
$add=function(array $r,string $kind)use(&$map){$phone=preg_replace('/\D+/','',(string)($r['customer_phone']??$r['member_phone']??''));$key=$phone?:('name:'.($r['customer_name']??$r['member_name']??'미상'));if(!isset($map[$key]))$map[$key]=['name'=>'','phone'=>'','estimates'=>0,'inquiries'=>0,'latest_estimate'=>'','latest_at'=>'','status'=>'','provider'=>'-'];$m=&$map[$key];$m['name']=$r['customer_name']??$r['member_name']??$m['name'];$m['phone']=$r['customer_phone']??$r['member_phone']??$m['phone'];if($kind==='estimate'){$m['estimates']++;if(($r['created_at']??'')>$m['latest_at']){$m['latest_at']=$r['created_at'];$m['latest_estimate']=$r['item']??'';$m['status']=$r['status']??'';}}else{$m['inquiries']++;}};
foreach(['estimate_direct'=>'SELECT customer_name,customer_phone,CONCAT(COALESCE(brand_name,\'\'),\' \',COALESCE(vehicle_name,\'\')) item,status,created_at FROM estimate_direct','estimate_quick'=>'SELECT customer_name,customer_phone,COALESCE(car_type,\'상담 후 결정\') item,status,created_at FROM estimate_quick'] as $t=>$sql){if(ag_table_exists($pdo,$t))try{foreach($pdo->query($sql) as $r)$add($r,'estimate');}catch(Throwable $e){}}
if(ag_table_exists($pdo,'customer_inquiries'))try{foreach($pdo->query('SELECT member_name,member_phone,created_at FROM customer_inquiries') as $r)$add($r,'inquiry');}catch(Throwable $e){}
$rows=array_values($map); if($q!=='')$rows=array_values(array_filter($rows,fn($r)=>str_contains($r['name'],$q)||str_contains($r['phone'],$q))); usort($rows,fn($a,$b)=>strcmp($b['latest_at'],$a['latest_at'])); $labels=ag_status_labels();
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>고객 관리 - 오토지니</title><link rel="stylesheet" href="./sidebar.css"><link rel="stylesheet" href="./customers-page.css"><link rel="stylesheet" href="./admin-ui.css"></head><body><div class="layout"><?php $currentAdminPage='customers';require __DIR__.'/sidebar.php';?><main class="main"><section class="card ag-page-card"><div class="top"><div><h1>고객 관리</h1><p>견적과 문의의 연락처를 기준으로 고객 활동을 통합해서 확인합니다.</p></div><div class="top-stats"><span class="stat">통합 고객 <b><?=number_format(count($rows))?></b></span></div></div><form class="filter-box ag-inline-filter" method="get"><div class="filter-item search"><span class="filter-label">검색어</span><div class="filter-control"><input type="search" name="q" value="<?=ag_h($q)?>" placeholder="고객명 / 휴대폰 검색"><button type="submit" class="primary">검색</button><a class="reset" href="./customers.php">초기화</a></div></div></form></section><section class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>이름</th><th>휴대폰</th><th>가입경로</th><th>견적 신청</th><th>문의</th><th>최근 견적</th><th>상담 상태</th><th>최근 활동</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=ag_h($r['name']?:'비회원')?></b></td><td><?=ag_h($r['phone']?:'-')?></td><td><?=ag_h($r['provider'])?></td><td class="count"><?=$r['estimates']?></td><td class="count"><?=$r['inquiries']?></td><td><?=ag_h(trim($r['latest_estimate'])?:'-')?></td><td><?php if($r['status']):?><span class="status"><?=ag_h($labels[$r['status']]??$r['status'])?></span><?php else:?>-<?php endif;?></td><td><?=ag_h($r['latest_at']?:'-')?></td></tr><?php endforeach;?></tbody></table></div></section></main></div></body></html>
