<?php
declare(strict_types=1);
require_once __DIR__.'/auth.php'; require_once __DIR__.'/../config/database.php'; require_once __DIR__.'/admin_helpers.php';
$q=trim((string)($_GET['q']??'')); $map=[];
$add=function(array $r,string $kind)use(&$map){$phone=preg_replace('/\D+/','',(string)($r['customer_phone']??$r['member_phone']??''));$key=$phone?:('name:'.($r['customer_name']??$r['member_name']??'미상'));if(!isset($map[$key]))$map[$key]=['name'=>'','phone'=>'','estimates'=>0,'inquiries'=>0,'latest_estimate'=>'','latest_at'=>'','status'=>'','provider'=>'-'];$m=&$map[$key];$m['name']=$r['customer_name']??$r['member_name']??$m['name'];$m['phone']=$r['customer_phone']??$r['member_phone']??$m['phone'];if($kind==='estimate'){$m['estimates']++;if(($r['created_at']??'')>$m['latest_at']){$m['latest_at']=$r['created_at'];$m['latest_estimate']=$r['item']??'';$m['status']=$r['status']??'';}}else{$m['inquiries']++;}};
foreach(['estimate_direct'=>'SELECT customer_name,customer_phone,CONCAT(COALESCE(brand_name,\'\'),\' \',COALESCE(vehicle_name,\'\')) item,status,created_at FROM estimate_direct','estimate_quick'=>'SELECT customer_name,customer_phone,COALESCE(car_type,\'상담 후 결정\') item,status,created_at FROM estimate_quick'] as $t=>$sql){if(ag_table_exists($pdo,$t))try{foreach($pdo->query($sql) as $r)$add($r,'estimate');}catch(Throwable $e){}}
if(ag_table_exists($pdo,'customer_inquiries'))try{foreach($pdo->query('SELECT member_name,member_phone,created_at FROM customer_inquiries') as $r)$add($r,'inquiry');}catch(Throwable $e){}
$rows=array_values($map); if($q!=='')$rows=array_values(array_filter($rows,fn($r)=>str_contains($r['name'],$q)||str_contains($r['phone'],$q))); usort($rows,fn($a,$b)=>strcmp($b['latest_at'],$a['latest_at'])); $labels=ag_status_labels();
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>고객 관리 - 오토지니</title><link rel="stylesheet" href="./sidebar.css"><style>*{box-sizing:border-box}body{margin:0;font:13px Pretendard,"Noto Sans KR",Arial,sans-serif;background:#eef5f8;color:#25384a}.layout{display:grid;grid-template-columns:228px minmax(0,1fr);min-height:100vh}.main{padding:28px}.head h1{margin:0;font-size:24px}.head p{color:#80919c}.filter{margin:18px 0;background:#fff;border:1px solid #d8e2e7;border-radius:8px;padding:14px;display:flex;gap:8px}.filter input{height:38px;min-width:280px;border:1px solid #cfd9df;border-radius:6px;padding:0 11px}.filter button{border:0;border-radius:6px;background:#3924b9;color:#fff;font-weight:800;padding:0 16px}.panel{background:#fff;border:1px solid #d8e2e7;border-radius:9px;padding:18px}.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:950px}.table th,.table td{padding:11px 9px;border-bottom:1px solid #edf1f3;text-align:left}.table th{font-size:11px;color:#748590}.count{font-weight:800;color:#3924b9}.status{display:inline-block;padding:4px 7px;border-radius:999px;background:#edf1ff;color:#405bd7;font-weight:700}@media(max-width:900px){.layout{grid-template-columns:1fr}.admin-sidebar{display:none}.main{padding:14px}}</style><link rel="stylesheet" href="./admin-ui.css"></head><body><div class="layout"><?php $currentAdminPage='customers';require __DIR__.'/sidebar.php';?><main class="main"><section class="card ag-page-card"><div class="top"><div><h1>고객 관리</h1><p>견적과 문의의 연락처를 기준으로 고객 활동을 통합해서 확인합니다.</p></div><div class="top-stats"><span class="stat">통합 고객 <b><?=number_format(count($rows))?></b></span></div></div><form class="filter-box ag-inline-filter" method="get"><div class="filter-item search"><span class="filter-label">검색어</span><div class="filter-control"><input type="search" name="q" value="<?=ag_h($q)?>" placeholder="고객명 / 휴대폰 검색"><button type="submit" class="primary">검색</button><a class="reset" href="./customers.php">초기화</a></div></div></form></section><section class="panel"><div class="table-wrap"><table class="table"><thead><tr><th>이름</th><th>휴대폰</th><th>가입경로</th><th>견적 신청</th><th>문의</th><th>최근 견적</th><th>상담 상태</th><th>최근 활동</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=ag_h($r['name']?:'비회원')?></b></td><td><?=ag_h($r['phone']?:'-')?></td><td><?=ag_h($r['provider'])?></td><td class="count"><?=$r['estimates']?></td><td class="count"><?=$r['inquiries']?></td><td><?=ag_h(trim($r['latest_estimate'])?:'-')?></td><td><?php if($r['status']):?><span class="status"><?=ag_h($labels[$r['status']]??$r['status'])?></span><?php else:?>-<?php endif;?></td><td><?=ag_h($r['latest_at']?:'-')?></td></tr><?php endforeach;?></tbody></table></div></section></main></div></body></html>
