<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../config/database.php';
function h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function scalar(PDO $pdo, string $sql, array $params=[]): int { try {$s=$pdo->prepare($sql);$s->execute($params);return (int)$s->fetchColumn();}catch(Throwable $e){return 0;} }
$total = scalar($pdo, "SELECT (SELECT COUNT(*) FROM estimate_direct)+(SELECT COUNT(*) FROM estimate_quick)");
$today = scalar($pdo, "SELECT (SELECT COUNT(*) FROM estimate_direct WHERE DATE(created_at)=CURDATE())+(SELECT COUNT(*) FROM estimate_quick WHERE DATE(created_at)=CURDATE())");
$new = scalar($pdo, "SELECT (SELECT COUNT(*) FROM estimate_direct WHERE status='NEW')+(SELECT COUNT(*) FROM estimate_quick WHERE status='NEW')");
$contracted = scalar($pdo, "SELECT (SELECT COUNT(*) FROM estimate_direct WHERE status='CONTRACTED')+(SELECT COUNT(*) FROM estimate_quick WHERE status='CONTRACTED')");
$completedSessions = scalar($pdo, "SELECT COUNT(*) FROM estimate_abandonments WHERE is_completed=1");
$allSessions = scalar($pdo, "SELECT COUNT(*) FROM estimate_abandonments");
$conversion = $allSessions > 0 ? round($completedSessions / $allSessions * 100, 1) : 0;
$sources=[];$vehicles=[];$funnel=[];$recent=[];
try {
$sources=$pdo->query("SELECT source, COUNT(*) cnt FROM (SELECT COALESCE(NULLIF(utm_source,''),'직접/기타') source FROM estimate_direct UNION ALL SELECT COALESCE(NULLIF(utm_source,''),'직접/기타') FROM estimate_quick) x GROUP BY source ORDER BY cnt DESC LIMIT 8")->fetchAll();
$vehicles=$pdo->query("SELECT vehicle_name, COUNT(*) cnt FROM estimate_direct WHERE vehicle_name IS NOT NULL GROUP BY vehicle_name ORDER BY cnt DESC LIMIT 8")->fetchAll();
$funnel=$pdo->query("SELECT stage_order, stage, COUNT(*) cnt FROM estimate_abandonments GROUP BY stage_order, stage ORDER BY stage_order")->fetchAll();
$recent=$pdo->query("SELECT * FROM (SELECT estimate_no,customer_name,vehicle_name AS item,status,created_at,'직접견적' type FROM estimate_direct UNION ALL SELECT estimate_no,customer_name,COALESCE(car_type,'상담 후 결정'),status,created_at,'간편견적' FROM estimate_quick) x ORDER BY created_at DESC LIMIT 10")->fetchAll();
} catch(Throwable $e) {}
$stageLabels=['LANDING'=>'유입','VEHICLE_LIST'=>'차량목록','VEHICLE_DETAIL'=>'차량상세','TRIM_SELECTED'=>'트림선택','CONDITIONS_SELECTED'=>'조건선택','ESTIMATE_FORM'=>'신청폼','CUSTOMER_INPUT'=>'정보입력','COMPLETED'=>'신청완료'];
$statusLabels=['NEW'=>'신규','CONTACTED'=>'상담중','REVIEWING'=>'심사중','APPROVED'=>'승인','CONTRACTED'=>'계약완료','CANCELED'=>'취소'];
?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>관리자 대시보드 - 오토지니</title><link rel="stylesheet" href="./sidebar.css"><style>
*{box-sizing:border-box}body{margin:0;font-family:Pretendard,"Noto Sans KR",Arial,sans-serif;background:#eef5f8;color:#25384a;font-size:13px}a{text-decoration:none;color:inherit}.layout{display:grid;grid-template-columns:264px 1fr;min-height:100vh}.side{background:#fff;border-right:1px solid #dbe4e9;padding:18px 14px;display:flex;flex-direction:column;gap:14px}
.admin-menu{margin-top:18px;display:grid;gap:14px}.admin-menu-group{padding:12px;border:1px solid #e5ebef;border-radius:14px;background:#fbfcfd}.admin-menu-group.current{border-color:#cfc9f4;background:#f7f5ff;box-shadow:0 0 0 1px rgba(57,36,185,.04) inset}.admin-menu-group p{font-size:11px;color:#778893;font-weight:800;margin:0 0 10px;letter-spacing:.02em}.admin-menu-link{display:flex;align-items:flex-start;gap:10px;padding:10px 11px;border:1px solid transparent;border-radius:10px;color:#5c7080;transition:.15s;background:transparent}.admin-menu-link + .admin-menu-link{margin-top:6px}.admin-menu-link:hover{background:#f2f6f9;border-color:#e0e7ec}.admin-menu-link.active{background:#3924b9;color:#fff;border-color:#3924b9;box-shadow:0 8px 18px rgba(57,36,185,.18)}.admin-menu-link.active .admin-menu-icon{background:rgba(255,255,255,.16);color:#fff}.admin-menu-link.active small{color:rgba(255,255,255,.82)}.admin-menu-icon{flex:0 0 34px;width:34px;height:34px;border-radius:10px;background:#eef2f7;color:#3924b9;font-size:11px;font-weight:800;display:grid;place-items:center}.admin-menu-text{display:block;min-width:0}.admin-menu-text strong{display:block;font-size:13px;line-height:1.3}.admin-menu-text small{display:block;margin-top:3px;font-size:11px;line-height:1.45;color:#81919b}.admin-tool-note{margin-top:14px;padding:11px 12px;border-radius:12px;background:#f6f9fb;border:1px solid #e5ecef}.admin-tool-note div{display:flex;justify-content:space-between;gap:10px;padding:4px 0}.admin-tool-note span{color:#7a8a94}.admin-tool-note b{color:#21384a}.admin-userbox{display:flex;gap:10px;align-items:center;padding-bottom:18px;border-bottom:1px solid #edf1f3}.admin-userbox .mark{width:38px;height:38px;border-radius:10px;background:#29bed1;color:#fff;display:grid;place-items:center;font-weight:800}.admin-userbox strong,.admin-userbox span,.admin-userbox small,.admin-userbox a{display:block}.admin-userbox strong{font-size:15px}.admin-userbox span{font-size:11px;color:#93a3ad;margin-top:2px}.admin-userbox .role{display:inline-block;margin-top:4px;padding:2px 6px;border-radius:999px;background:#eef2ff;color:#4338ca;font-size:10px;font-weight:800}.admin-userbox .logout{margin-top:5px;font-size:11px;color:#25bcd0;text-decoration:none}.admin-userbox .logout:hover{text-decoration:underline}
.main{padding:28px}.head{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}.head h1{margin:0;font-size:24px}.head p{margin:6px 0 0;color:#80919c}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:14px}.metric,.panel{background:#fff;border:1px solid #d8e2e7;border-radius:8px}.metric{padding:18px}.metric span{color:#7d8e99;font-size:12px}.metric strong{display:block;margin-top:8px;font-size:25px;color:#24394a}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{padding:18px;margin-bottom:14px}.panel h2{margin:0 0 14px;font-size:16px}.bar-row{display:grid;grid-template-columns:110px 1fr 45px;align-items:center;gap:10px;margin:10px 0}.bar{height:8px;background:#eef1f4;border-radius:999px;overflow:hidden}.bar i{display:block;height:100%;background:#3924b9;border-radius:inherit}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px 8px;border-bottom:1px solid #edf1f3;text-align:left}.table th{font-size:11px;color:#81919b}.pill{display:inline-flex;padding:4px 7px;border-radius:999px;background:#edf1ff;color:#405bd7;font-size:11px;font-weight:700}.actions{display:flex;gap:8px}.btn{background:#3924b9;color:#fff;padding:9px 12px;border-radius:5px;font-weight:700}.btn.sub{background:#fff;color:#3924b9;border:1px solid #cfc9f4}@media(max-width:1100px){.cards{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:920px){.layout{grid-template-columns:1fr}.side{display:none}.main{padding:14px}.cards{grid-template-columns:1fr 1fr}}@media(max-width:640px){.cards{grid-template-columns:1fr}}
.layout{grid-template-columns:228px minmax(0,1fr)!important}@media(max-width:900px){.layout{grid-template-columns:1fr!important}}</style></head><body><div class="layout"><?php $currentAdminPage = 'dashboard'; require __DIR__ . '/sidebar.php'; ?><main class="main"><div class="head"><div><h1>운영 대시보드</h1><p>견적 신청·유입경로·이탈구간을 한눈에 확인합니다.</p></div><div class="actions"><a class="btn" href="./estimates.php">견적 신청 관리</a></div></div>
<div class="cards"><div class="metric"><span>오늘 견적</span><strong><?=number_format($today)?></strong></div><div class="metric"><span>전체 견적</span><strong><?=number_format($total)?></strong></div><div class="metric"><span>신규 상담</span><strong><?=number_format($new)?></strong></div><div class="metric"><span>계약 완료</span><strong><?=number_format($contracted)?></strong></div><div class="metric"><span>견적 완료율</span><strong><?=h($conversion)?>%</strong></div></div>
<div class="grid"><section class="panel"><h2>유입경로 TOP</h2><?php $max=max(array_map(fn($r)=>(int)$r['cnt'],$sources)?:[1]); foreach($sources as $r):?><div class="bar-row"><span><?=h($r['source'])?></span><div class="bar"><i style="width:<?=max(3,(int)$r['cnt']/$max*100)?>%"></i></div><b><?=number_format((int)$r['cnt'])?></b></div><?php endforeach;if(!$sources):?><p>아직 유입 데이터가 없습니다.</p><?php endif;?></section>
<section class="panel"><h2>인기 차량 TOP</h2><?php $maxv=max(array_map(fn($r)=>(int)$r['cnt'],$vehicles)?:[1]); foreach($vehicles as $r):?><div class="bar-row"><span><?=h($r['vehicle_name'])?></span><div class="bar"><i style="width:<?=max(3,(int)$r['cnt']/$maxv*100)?>%"></i></div><b><?=number_format((int)$r['cnt'])?></b></div><?php endforeach;if(!$vehicles):?><p>아직 차량 견적 데이터가 없습니다.</p><?php endif;?></section></div>
<section class="panel"><h2>견적 퍼널 / 이탈 단계</h2><div style="display:grid;grid-template-columns:repeat(8,1fr);gap:8px;overflow:auto"><?php foreach($funnel as $r):?><div style="min-width:100px;padding:13px 10px;background:#f7f9fb;border-radius:7px;text-align:center"><div style="color:#7c8d98;font-size:11px"><?=h($stageLabels[$r['stage']]??$r['stage'])?></div><strong style="display:block;margin-top:6px;font-size:20px"><?=number_format((int)$r['cnt'])?></strong></div><?php endforeach;?></div><?php if(!$funnel):?><p>이탈 추적 데이터가 없습니다. analytics_migration.sql 실행 후 사용자 유입부터 집계됩니다.</p><?php endif;?></section>
<section class="panel"><h2>최근 견적</h2><table class="table"><thead><tr><th>구분</th><th>견적번호</th><th>고객</th><th>차량/관심차종</th><th>상태</th><th>신청일</th></tr></thead><tbody><?php foreach($recent as $r):?><tr><td><span class="pill"><?=h($r['type'])?></span></td><td><?=h($r['estimate_no'])?></td><td><?=h($r['customer_name'])?></td><td><?=h($r['item'])?></td><td><?=h($statusLabels[$r['status']]??$r['status'])?></td><td><?=h($r['created_at'])?></td></tr><?php endforeach;?></tbody></table></section>
</main></div></body></html>